### PR TITLE
Throw error for invalid ports

### LINKED ISSUE #5: fails to detect invalid URL
The following URL is accepted by `@cliqz/url-parser` but rejected by `URL` constructor in Firefox/Node.js: `http://data:text/plain;charset=UTF-8;page=21,the%20data:1234,5678`.

### PR DESCRIPTION
**Pull request by sammacbeth**
If the port specified in the URL is not numeric, or greater than 2^16, the URL constructor should throw. This PR adds checks for these cases.

Fixes #5. Adds test to verify #6 is working.

### CODE REVIEW

File: lib/url.ts [hunk 1]
```diff
@@ -442,11 +443,22 @@ export default class URL implements IURL {
...
       }
       if (!this._port) {
         this._port = this.href.slice(portStart, i);
       }
+      // validate port - cannot contain non-numeric characters
+      if (nonNumeric) {
+        throw new TypeError('Invalid URL: port contains non numeric character');
+      }
+      // cannot be greater than 65535
+      if (this._port.length >= 5 && parseInt(this._port, 10) > 65535) {
```
Comment (remusao) [inline lib/url.ts]: What about using `Number(this._port)` instead? It's a bit more strict than `parseInt`.
